server {
    listen 80;
    server_name localhost;

    # Localização padrão: serve os arquivos do Flutter Web
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html; # Essencial para o roteamento do Flutter Web
    }

    # Localização da API: redireciona para o backend Quarkus
    location /api/ {
        # O nome 'backend' é o nome do serviço definido no docker-compose.yml
        proxy_pass http://backend:8080/;

        # Cabeçalhos para manter a informação da requisição original
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Tratamento de erros
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
